//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HostMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Establishment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Establishment()
        {
            this.Rooms = new HashSet<Room>();
        }

        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "ID Cidade")]
        public int IdCity { get; set; }
        [Display(Name = "ID Categoria")]
        public int IdCategory { get; set; }
        [Display(Name = "Nome")]
        public string Name { get; set; }
        [Display(Name = "Endereço")]
        public string Address { get; set; }
        [Display(Name = "Telefone")]
        public string Telephone { get; set; }
        [Display(Name = "Site")]
        public string Site { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
