//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HostMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [Display(Name = "ID Estabelecimento")]
        public int IdEstablishment { get; set; }
        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "ID Tipo de Sala")]
        public int IdRoomKind { get; set; }
        [Display(Name = "Disponível")]
        public bool Available { get; set; }
    
        public virtual Establishment Establishment { get; set; }
        public virtual RoomKind RoomKind { get; set; }
    }
}
